// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwV6-qoCCDCFJZtZ0K8Y391YWvtBZNhuM',
    appId: '1:901234658011:web:fc11b7466077e43241dafe',
    messagingSenderId: '901234658011',
    projectId: 'siaga-kota',
    authDomain: 'siaga-kota.firebaseapp.com',
    storageBucket: 'siaga-kota.firebasestorage.app',
    measurementId: 'G-1L20ZBWWB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlq0yCM2psXc-O_3EeyJCvY1vCRkiwoR4',
    appId: '1:901234658011:android:36fb960615463bba41dafe',
    messagingSenderId: '901234658011',
    projectId: 'siaga-kota',
    storageBucket: 'siaga-kota.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwei543IYVlRl8WnIRMwrJBIYjTNxQrvk',
    appId: '1:901234658011:ios:8efcbcc88adc1a4c41dafe',
    messagingSenderId: '901234658011',
    projectId: 'siaga-kota',
    storageBucket: 'siaga-kota.firebasestorage.app',
    iosBundleId: 'com.example.siagakotaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwei543IYVlRl8WnIRMwrJBIYjTNxQrvk',
    appId: '1:901234658011:ios:8efcbcc88adc1a4c41dafe',
    messagingSenderId: '901234658011',
    projectId: 'siaga-kota',
    storageBucket: 'siaga-kota.firebasestorage.app',
    iosBundleId: 'com.example.siagakotaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwV6-qoCCDCFJZtZ0K8Y391YWvtBZNhuM',
    appId: '1:901234658011:web:b93f96b8620f6e4841dafe',
    messagingSenderId: '901234658011',
    projectId: 'siaga-kota',
    authDomain: 'siaga-kota.firebaseapp.com',
    storageBucket: 'siaga-kota.firebasestorage.app',
    measurementId: 'G-M9DFEHF9PD',
  );
}
